#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
DATA_ROOT="${DATA_ROOT:-$ROOT/dataset/table4_extension}"
OUTPUT_ROOT="${OUTPUT_ROOT:-$ROOT/model/diffusion-vs-ar/output/extension}"
GPUS="${GPUS:-auto}"
SIZES="${SIZES:-4x4,16x16,25x25}"
EPOCHS="${EPOCHS:-12}"
BATCH_SIZE="${BATCH_SIZE:-64}"
LEARNING_RATE="${LEARNING_RATE:-3e-4}"
NUM_WORKERS="${NUM_WORKERS:-4}"
SEED="${SEED:-42}"
EASY_WEIGHT="${EASY_WEIGHT:-1.0}"
MEDIUM_WEIGHT="${MEDIUM_WEIGHT:-1.5}"
HARD_WEIGHT="${HARD_WEIGHT:-3.0}"
UNKNOWN_RATIO_WEIGHT="${UNKNOWN_RATIO_WEIGHT:-0.5}"
EVAL_SPLIT="${EVAL_SPLIT:-test}"
EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-128}"
EVAL_EVERY="${EVAL_EVERY:-1}"
DISABLE_WEIGHTED_SAMPLING="${DISABLE_WEIGHTED_SAMPLING:-0}"
HIDDEN_SIZE="${HIDDEN_SIZE:-512}"
NUM_LAYERS="${NUM_LAYERS:-6}"
NUM_HEADS="${NUM_HEADS:-8}"
DROPOUT="${DROPOUT:-0.1}"
DIFFUSION_STEPS="${DIFFUSION_STEPS:-20}"
TOKEN_REWEIGHTING="${TOKEN_REWEIGHTING:-1}"
LOSS_ALPHA="${LOSS_ALPHA:-0.25}"
LOSS_GAMMA="${LOSS_GAMMA:-1.0}"
TIME_REWEIGHTING="${TIME_REWEIGHTING:-linear}"
LR_SCHEDULER="${LR_SCHEDULER:-cosine}"
WARMUP_RATIO="${WARMUP_RATIO:-0.03}"
GRAD_ACC_STEPS="${GRAD_ACC_STEPS:-1}"
MAX_GRAD_NORM="${MAX_GRAD_NORM:-1.0}"

echo "[extension] training generalized sudoku family model"
echo "  data_root   : $DATA_ROOT"
echo "  output_root : $OUTPUT_ROOT"
echo "  gpus        : $GPUS"
echo "  sizes       : $SIZES"
echo "  epochs      : $EPOCHS"
echo "  batch_size  : $BATCH_SIZE"
echo "  lr          : $LEARNING_RATE"
echo "  workers     : $NUM_WORKERS"
echo "  seed        : $SEED"
echo "  weights     : easy=$EASY_WEIGHT medium=$MEDIUM_WEIGHT hard=$HARD_WEIGHT unknown_ratio=$UNKNOWN_RATIO_WEIGHT"
echo "  eval        : split=$EVAL_SPLIT batch=$EVAL_BATCH_SIZE every=$EVAL_EVERY"
echo "  mdm         : steps=$DIFFUSION_STEPS token_rw=$TOKEN_REWEIGHTING alpha=$LOSS_ALPHA gamma=$LOSS_GAMMA time_rw=$TIME_REWEIGHTING"
echo "  optim       : scheduler=$LR_SCHEDULER warmup=$WARMUP_RATIO grad_acc=$GRAD_ACC_STEPS max_grad_norm=$MAX_GRAD_NORM"
echo "  model       : hidden=$HIDDEN_SIZE layers=$NUM_LAYERS heads=$NUM_HEADS dropout=$DROPOUT"

CMD=(
  python3 "$ROOT/model/diffusion-vs-ar/scripts/extension/train_family_model.py"
  --family gen_sudoku
  --data-root "$DATA_ROOT"
  --output-root "$OUTPUT_ROOT"
  --sizes "$SIZES"
  --gpus "$GPUS"
  --epochs "$EPOCHS"
  --batch-size "$BATCH_SIZE"
  --learning-rate "$LEARNING_RATE"
  --num-workers "$NUM_WORKERS"
  --seed "$SEED"
  --easy-weight "$EASY_WEIGHT"
  --medium-weight "$MEDIUM_WEIGHT"
  --hard-weight "$HARD_WEIGHT"
  --unknown-ratio-weight "$UNKNOWN_RATIO_WEIGHT"
  --eval-split "$EVAL_SPLIT"
  --eval-batch-size "$EVAL_BATCH_SIZE"
  --eval-every "$EVAL_EVERY"
  --hidden-size "$HIDDEN_SIZE"
  --num-layers "$NUM_LAYERS"
  --num-heads "$NUM_HEADS"
  --dropout "$DROPOUT"
  --diffusion-steps "$DIFFUSION_STEPS"
  --loss-alpha "$LOSS_ALPHA"
  --loss-gamma "$LOSS_GAMMA"
  --time-reweighting "$TIME_REWEIGHTING"
  --lr-scheduler "$LR_SCHEDULER"
  --warmup-ratio "$WARMUP_RATIO"
  --gradient-accumulation-steps "$GRAD_ACC_STEPS"
  --max-grad-norm "$MAX_GRAD_NORM"
)
if [[ "$DISABLE_WEIGHTED_SAMPLING" == "1" ]]; then
  CMD+=(--disable-weighted-sampling)
fi
if [[ "$TOKEN_REWEIGHTING" == "0" ]]; then
  CMD+=(--disable-token-reweighting)
fi
"${CMD[@]}"
